targets:
  $default:
    builders:
      darbiw:
        generate_for:
          - example/**
      source_gen:combining_builder:
        options:
          ignore_for_file:
            - non_constant_identifier_names

builders:
  darbiw:
    import: "package:darbiw/builder.dart"
    builder_factories: ["generator"]
    build_extensions: { ".dart": [".binary.g.part"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen:combining_builder"]
