name: darbiw
description: Dart binary encoder/decoder with code generation for classes
version: 1.0.0
repository: https://github.com/tomasweigenast/darbiw

environment:
  sdk: ^3.3.3

dependencies:
  analyzer: ^6.4.1
  build: ^2.4.1
  dart_style: ^2.3.6
  meta: ^1.14.0
  source_gen: ^1.5.0

dev_dependencies:
  build_runner: ^2.4.9
  lints: ^4.0.0
  test: ^1.24.0
